import { AppColors } from '@/constants/colors';
import { StyleSheet } from 'react-native';

import { createThemedStyles } from './foundations';
import {
  sharedAvatarImageFill,
  sharedBrandDotBase,
  sharedBrandPillBase,
  sharedBrandPillTextBase,
  sharedHeaderActionPressed,
  sharedHeroDecorCircleOne,
  sharedHeroDecorCircleTwo,
  sharedLoginPillBase,
  sharedLoginPillText,
  sharedPressedScale,
  sharedSmallAvatarBase,
} from './shared-primitives';

export const createInvestorTabStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    hero: {
      minHeight: 230,
      backgroundColor: Colors.primary,
      paddingHorizontal: 24,
      paddingBottom: 28,
      overflow: 'hidden',
    },
    heroDecorCircleOne: {
      ...sharedHeroDecorCircleOne,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    heroDecorCircleTwo: {
      ...sharedHeroDecorCircleTwo,
      borderColor: 'rgba(255,255,255,0.12)',
      bottom: -92,
    },
    kicker: {
      fontSize: 13,
      fontWeight: '800',
      color: 'rgba(255,255,255,0.76)',
      marginBottom: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    heroTitle: {
      color: '#FFFFFF',
      fontSize: 32,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    subtitle: {
      fontSize: 15,
      lineHeight: 22,
      color: 'rgba(255,255,255,0.8)',
      maxWidth: 340,
    },
    contentPanel: {
      backgroundColor: Colors.background,
      borderTopLeftRadius: 34,
      borderTopRightRadius: 34,
      paddingTop: 18,
      marginTop: -29,
    },
    card: {
      overflow: 'hidden',
      backgroundColor: Colors.surface,
      marginHorizontal: 20,
      borderRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 22,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: {
        width: 0,
        height: 10,
      },
      elevation: 4,
    },
    cardAccent: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 5,
      backgroundColor: Colors.accent,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    cardBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: Colors.tag,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    cardBadgeText: {
      color: Colors.accent,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    cardIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 16,
      backgroundColor: Colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: Colors.accent,
      shadowOpacity: 0.18,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    cardTitle: {
      fontSize: 24,
      fontWeight: '900',
      color: Colors.textPrimary,
      marginBottom: 10,
      letterSpacing: -0.6,
    },
    cardText: {
      fontSize: 14,
      lineHeight: 22,
      color: Colors.textSecondary,
      marginBottom: 18,
    },
    benefitsList: {
      gap: 12,
      marginBottom: 22,
    },
    benefitItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    benefitDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginTop: 5,
      backgroundColor: Colors.accent,
    },
    benefitText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 20,
      color: Colors.textSecondary,
      fontWeight: '600',
    },
    button: {
      backgroundColor: Colors.accent,
      borderRadius: 18,
      paddingVertical: 15,
      paddingHorizontal: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    buttonPressed: sharedPressedScale,
    buttonText: {
      color: Colors.white,
      fontSize: 15,
      fontWeight: '900',
    },
    brandPill: {
      ...sharedBrandPillBase,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      marginBottom: 12,
    },
    brandDot: {
      ...sharedBrandDotBase,
      backgroundColor: Colors.logoGreenLight,
    },
    brandPillText: {
      ...sharedBrandPillTextBase,
      color: Colors.white,
      textTransform: 'uppercase',
    },
    heroHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    heroSubtitle: {
      marginTop: 10,
      maxWidth: 290,
      color: 'rgba(255,255,255,0.72)',
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '600',
    },
  }),
);

export const createHomeDashboardStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    content: {
      paddingBottom: 32,
    },
    hero: {
      minHeight: 300,
      marginHorizontal: 18,
      borderRadius: 30,
      overflow: 'hidden',
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 26,
      justifyContent: 'space-between',
      backgroundColor: Colors.accentDark,
    },
    heroImage: {
      borderRadius: 30,
    },
    heroOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 34, 24, 0.56)',
    },
    heroGlow: {
      position: 'absolute',
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: 'rgba(79, 196, 122, 0.20)',
      top: -60,
      right: -50,
    },
    heroHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    brandBadge: {
      backgroundColor: 'rgba(0, 23, 28, 0.85)',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    brandBadgeText: {
      color: Colors.textOnDark,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 1.2,
    },
    brandDot: {
      ...sharedBrandDotBase,
      backgroundColor: Colors.logoGreenLight,
    },
    brandPillText: {
      ...sharedBrandPillTextBase,
      color: Colors.white,
    },
    brandPill: {
      ...sharedBrandPillBase,
      borderColor: 'rgba(255, 255, 255, 0.14)',
      backgroundColor: 'rgba(0, 23, 28, 0.63)',
    },
    helpPillText: {
      color: Colors.white,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '900',
    },
    heroBody: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 16,
    },
    heroCopy: {
      flex: 1,
    },
    kicker: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 10,
    },
    heroTitle: {
      color: Colors.textOnDark,
      fontSize: 32,
      lineHeight: 38,
      fontWeight: '900',
      letterSpacing: -0.9,
    },
    heroSubtitle: {
      marginTop: 12,
      color: 'rgba(255,255,255,0.82)',
      fontSize: 14,
      lineHeight: 21,
      maxWidth: 330,
    },
    avatarImage: {
      ...sharedAvatarImageFill,
    },
    quickActionsRow: {
      marginTop: 18,
      marginHorizontal: 18,
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    quickAction: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 6,
    },
    quickActionIconBox: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: Colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    quickActionLabel: {
      color: Colors.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    section: {
      marginTop: 28,
    },
    sectionHeader: {
      paddingHorizontal: 18,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 14,
    },
    sectionTitle: {
      color: Colors.textPrimary,
      fontSize: 25,
      fontWeight: '900',
      letterSpacing: -0.7,
    },
    sectionSubtitle: {
      color: Colors.textMuted,
      fontSize: 13,
      marginTop: 4,
      fontWeight: '600',
    },
    linkButton: {
      paddingVertical: 6,
    },
    linkText: {
      color: Colors.accent,
      fontSize: 13,
      fontWeight: '800',
    },
    projectRow: {
      paddingLeft: 18,
      paddingRight: 6,
      paddingTop: 18,
      gap: 14,
    },
    projectCard: {
      width: 280,
      borderRadius: 24,
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.border,
      overflow: 'hidden',
      shadowColor: Colors.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    projectImage: {
      width: '100%',
      height: 158,
      backgroundColor: Colors.surfaceMuted,
    },
    projectContent: {
      padding: 16,
    },
    projectBadge: {
      alignSelf: 'flex-start',
      backgroundColor: Colors.tag,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      marginBottom: 10,
    },
    projectBadgeText: {
      color: Colors.tagText,
      fontSize: 11,
      fontWeight: '900',
    },
    projectName: {
      color: Colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: 8,
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    locationText: {
      flex: 1,
      color: Colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    projectPrice: {
      color: Colors.accent,
      fontSize: 24,
      fontWeight: '900',
      marginTop: 14,
      letterSpacing: -0.4,
    },
    projectFooter: {
      marginTop: 14,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    projectMeta: {
      flex: 1,
      color: Colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    reservePill: {
      backgroundColor: Colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
    },
    reservePillText: {
      color: Colors.textOnDark,
      fontSize: 12,
      fontWeight: '900',
    },
    locationList: {
      paddingLeft: 18,
      paddingRight: 6,
      paddingTop: 18,
      gap: 12,
    },
    locationChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: Colors.surface,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    locationInitials: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: Colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    locationInitialsText: {
      color: Colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
    },
    locationChipText: {
      color: Colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
      maxWidth: 140,
    },
    spotlightCard: {
      marginTop: 28,
      marginHorizontal: 18,
      borderRadius: 28,
      overflow: 'hidden',
      shadowColor: Colors.primary,
      shadowOpacity: 0.08,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    spotlightBackground: {
      minHeight: 214,
      justifyContent: 'flex-end',
    },
    spotlightImage: {
      borderRadius: 28,
    },
    spotlightOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 44, 34, 0.58)',
    },
    spotlightContent: {
      padding: 22,
    },
    spotlightTextWrap: {
      maxWidth: 240,
    },
    spotlightTitle: {
      color: Colors.textOnDark,
      fontSize: 30,
      lineHeight: 34,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    spotlightText: {
      marginTop: 10,
      color: 'rgba(255,255,255,0.82)',
      fontSize: 14,
      lineHeight: 21,
    },
    spotlightButton: {
      marginTop: 18,
      alignSelf: 'flex-start',
      backgroundColor: Colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 999,
    },
    spotlightButtonText: {
      color: Colors.primary,
      fontSize: 13,
      fontWeight: '900',
    },
    pressed: sharedPressedScale,
    loginPillText: sharedLoginPillText,
    loginPill: {
      ...sharedLoginPillBase,
      backgroundColor: Colors.primary,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    headerActionPressed: sharedHeaderActionPressed,
    avatar: {
      ...sharedSmallAvatarBase,
      backgroundColor: Colors.primaryLight,
      borderColor: 'rgba(255,255,255,0.24)',
    },
  }),
);

export const createPropertiesScreenStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    list: {
      paddingBottom: 28,
    },
    hero: {
      minHeight: 228,
      backgroundColor: Colors.primary,
      paddingHorizontal: 22,
      paddingTop: 22,
      paddingBottom: 42,
      overflow: 'hidden',
    },
    heroDecorCircleOne: {
      ...sharedHeroDecorCircleOne,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    heroDecorCircleTwo: {
      ...sharedHeroDecorCircleTwo,
      borderColor: 'rgba(255,255,255,0.12)',
      bottom: -80,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    headerTextGroup: {
      flex: 1,
      paddingRight: 18,
    },
    brandPill: {
      ...sharedBrandPillBase,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      marginBottom: 12,
    },
    brandDot: {
      ...sharedBrandDotBase,
      backgroundColor: Colors.logoGreenLight,
    },
    brandPillText: {
      ...sharedBrandPillTextBase,
      color: Colors.white,
    },
    greeting: {
      fontSize: 13,
      color: 'rgba(255,255,255,0.82)',
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    headline: {
      fontSize: 31,
      lineHeight: 38,
      fontWeight: '900',
      color: '#FFFFFF',
      letterSpacing: -0.9,
      maxWidth: 300,
    },
    subtitle: {
      marginTop: 10,
      fontSize: 14,
      lineHeight: 21,
      color: 'rgba(255,255,255,0.82)',
      maxWidth: 320,
    },
    avatar: {
      ...sharedSmallAvatarBase,
      backgroundColor: Colors.primaryLight,
      borderColor: 'rgba(255,255,255,0.24)',
    },
    avatarText: {
      color: '#FFFFFF',
      fontWeight: '900',
      fontSize: 15,
    },
    loginPill: {
      ...sharedLoginPillBase,
      backgroundColor: Colors.primary,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    loginPillText: sharedLoginPillText,
    headerActionPressed: sharedHeaderActionPressed,
    contentPanel: {
      marginTop: -33,
      backgroundColor: Colors.surface,
      borderTopLeftRadius: 34,
      borderTopRightRadius: 34,
      paddingTop: 22,
      paddingHorizontal: 20,
      paddingBottom: 16,
      shadowColor: Colors.primary,
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: {
        width: 0,
        height: -8,
      },
      elevation: 6,
    },
    searchWrap: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.background,
      borderRadius: 28,
      borderWidth: 1.4,
      borderColor: Colors.border,
      paddingHorizontal: 16,
    },
    searchWrapFocused: {
      backgroundColor: Colors.surface,
      borderColor: Colors.accent,
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: Colors.textPrimary,
      paddingVertical: 14,
    },
    filters: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 16,
    },
    filterBtn: {
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: Colors.background,
      borderWidth: 1.3,
      borderColor: Colors.border,
    },
    filterBtnActive: {
      backgroundColor: Colors.accent,
      borderColor: Colors.accent,
    },
    filterBtnPressed: sharedPressedScale,
    filterText: {
      fontSize: 13,
      color: Colors.textSecondary,
      fontWeight: '800',
    },
    filterTextActive: {
      color: '#FFFFFF',
    },
    sectionHeader: {
      marginTop: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: Colors.textPrimary,
      letterSpacing: -0.4,
    },
    resultCount: {
      fontSize: 13,
      color: Colors.textMuted,
      fontWeight: '600',
      marginTop: 3,
    },
    sortPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: Colors.tag,
    },
    sortPillPressed: sharedPressedScale,
    sortText: {
      color: Colors.accent,
      fontSize: 12,
      fontWeight: '900',
    },
    empty: {
      alignItems: 'center',
      paddingTop: 70,
      paddingHorizontal: 32,
    },
    emptyIconWrap: {
      width: 78,
      height: 78,
      borderRadius: 39,
      backgroundColor: Colors.tag,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: Colors.textPrimary,
      marginBottom: 6,
    },
    emptyText: {
      fontSize: 14,
      lineHeight: 21,
      color: Colors.textMuted,
      textAlign: 'center',
    },
    avatarImage: {
      ...sharedAvatarImageFill,
      borderRadius: 41,
    },
  }),
);

export const createInvestorDashboardStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scroll: { flex: 1, backgroundColor: Colors.background },
    scrollContent: { paddingBottom: 98 },
    heroShell: {
      marginHorizontal: 18,
      backgroundColor: Colors.primary,
      borderRadius: 30,
      overflow: 'hidden',
      paddingHorizontal: 22,
      paddingTop: 22,
      paddingBottom: 24,
    },
    heroDecorCircleOne: {
      ...sharedHeroDecorCircleOne,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    heroDecorCircleTwo: {
      ...sharedHeroDecorCircleTwo,
      borderColor: 'rgba(255,255,255,0.12)',
      bottom: -92,
    },
    heroHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 18,
    },
    heroKicker: {
      fontSize: 13,
      fontWeight: '800',
      color: 'rgba(255,255,255,0.76)',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    heroTitle: {
      color: Colors.white,
      fontSize: 32,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    heroIconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: Colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    heroCard: {
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderRadius: 24,
      padding: 22,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
    },
    heroLeft: { flex: 1 },
    heroLabel: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    heroValue: {
      color: Colors.white,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 10,
    },
    heroBadge: {
      backgroundColor: Colors.accent,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      alignSelf: 'flex-start',
    },
    heroBadgeText: {
      color: Colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    heroRight: { marginLeft: 16 },
    miniCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      borderWidth: 2,
      borderColor: Colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.primaryLight,
    },
    miniCircleVal: {
      color: Colors.white,
      fontSize: 22,
      fontWeight: '800',
    },
    miniCircleLabel: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: 10,
      fontWeight: '600',
      marginTop: -2,
    },
    statsRow: {
      paddingHorizontal: 18,
      gap: 12,
      paddingTop: 18,
      paddingBottom: 4,
      marginBottom: 6,
    },
    statCard: {
      backgroundColor: Colors.surface,
      borderRadius: 20,
      padding: 16,
      width: 130,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    statLabel: {
      fontSize: 11,
      color: Colors.textMuted,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    statValue: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 8,
    },
    statBadge: {
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
      alignSelf: 'flex-start',
    },
    statBadgePos: { backgroundColor: Colors.tag },
    statBadgeNeg: { backgroundColor: '#FEF2F2' },
    statChange: { fontSize: 11, fontWeight: '700' },
    statChangePos: { color: Colors.tagText },
    statChangeNeg: { color: Colors.error },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 18,
      marginTop: 24,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: Colors.textPrimary,
      letterSpacing: -0.4,
    },
    sectionAction: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.accent,
    },
    qaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      gap: 12,
    },
    qaItem: { flex: 1, alignItems: 'center' },
    qaIconBox: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: Colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    qaLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: Colors.textSecondary,
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    propCard: {
      marginHorizontal: 18,
      marginBottom: 12,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      overflow: 'hidden',
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.05,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 3 },
      elevation: 3,
    },
    propStrip: {
      width: 4,
      backgroundColor: Colors.accent,
    },
    propContent: {
      flex: 1,
      padding: 16,
    },
    propTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    propName: {
      fontSize: 17,
      fontWeight: '900',
      color: Colors.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 6,
    },
    propLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    propLocation: {
      flex: 1,
      fontSize: 12,
      color: Colors.textMuted,
      fontWeight: '600',
    },
    statusBadge: {
      borderRadius: 8,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    saleStatus: { backgroundColor: Colors.tag },
    leaseStatus: { backgroundColor: '#FEF9EC' },
    statusText: { fontSize: 11, fontWeight: '700' },
    saleStatusText: { color: Colors.tagText },
    leaseStatusText: { color: '#92400E' },
    propDivider: {
      height: 1,
      backgroundColor: Colors.border,
      marginVertical: 12,
      opacity: 0.5,
    },
    propMetrics: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    propMetric: { flex: 1, alignItems: 'center' },
    metricLabel: {
      fontSize: 10,
      color: Colors.textMuted,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 3,
    },
    metricValue: {
      fontSize: 13,
      fontWeight: '800',
      color: Colors.textPrimary,
      letterSpacing: -0.2,
    },
    metricSep: {
      width: 1,
      height: 28,
      backgroundColor: Colors.border,
      opacity: 0.5,
    },
    propFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    typeBadge: {
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    typeBadgeText: { fontSize: 11, fontWeight: '700' },
    acquiredText: {
      fontSize: 11,
      color: Colors.textMuted,
      fontWeight: '500',
    },
    txCard: {
      marginHorizontal: 18,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    txRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      gap: 12,
    },
    txIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    txIconPos: { backgroundColor: Colors.tag },
    txIconNeg: { backgroundColor: '#FEF2F2' },
    txLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.textPrimary,
      marginBottom: 2,
    },
    txDate: { fontSize: 11, color: Colors.textMuted, fontWeight: '500' },
    txAmount: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
    txPos: { color: Colors.accent },
    txNeg: { color: Colors.error },
    txDivider: {
      height: 1,
      backgroundColor: Colors.border,
      opacity: 0.4,
    },
  }),
);
