import { AppColors } from '@/constants/colors';
import { Dimensions, StyleSheet } from 'react-native';

import { createThemedStyles } from './foundations';
import {
  sharedAvatarImageFill,
  sharedBrandDotBase,
  sharedBrandPillBase,
  sharedBrandPillTextBase,
  sharedHeaderActionPressed,
  sharedHeroDecorCircleOne,
  sharedHeroDecorCircleTwo,
  sharedLoginPillBase,
  sharedLoginPillText,
  sharedPressedScale,
  sharedSmallAvatarBase,
} from './shared-primitives';

const { width } = Dimensions.get('window');

export const createInvestorTabStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    hero: {
      minHeight: 230,
      backgroundColor: Colors.primary,
      paddingHorizontal: 24,
      paddingBottom: 28,
      overflow: 'hidden',
    },
    heroDecorCircleOne: {
      ...sharedHeroDecorCircleOne,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    heroDecorCircleTwo: {
      ...sharedHeroDecorCircleTwo,
      borderColor: 'rgba(255,255,255,0.12)',
      bottom: -92,
    },
    kicker: {
      fontSize: 13,
      fontWeight: '800',
      color: 'rgba(255,255,255,0.76)',
      marginBottom: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    heroTitle: {
      color: '#FFFFFF',
      fontSize: 32,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    subtitle: {
      fontSize: 15,
      lineHeight: 22,
      color: 'rgba(255,255,255,0.8)',
      maxWidth: 340,
    },
    contentPanel: {
      backgroundColor: Colors.background,
      borderTopLeftRadius: 34,
      borderTopRightRadius: 34,
      paddingTop: 18,
      marginTop: -29,
    },
    card: {
      overflow: 'hidden',
      backgroundColor: Colors.surface,
      marginHorizontal: 20,
      borderRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 22,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: {
        width: 0,
        height: 10,
      },
      elevation: 4,
    },
    cardAccent: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 5,
      backgroundColor: Colors.accent,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    cardBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: Colors.tag,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    cardBadgeText: {
      color: Colors.accent,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    cardIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 16,
      backgroundColor: Colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: Colors.accent,
      shadowOpacity: 0.18,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    cardTitle: {
      fontSize: 24,
      fontWeight: '900',
      color: Colors.textPrimary,
      marginBottom: 10,
      letterSpacing: -0.6,
    },
    cardText: {
      fontSize: 14,
      lineHeight: 22,
      color: Colors.textSecondary,
      marginBottom: 18,
    },
    benefitsList: {
      gap: 12,
      marginBottom: 22,
    },
    benefitItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    benefitDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginTop: 5,
      backgroundColor: Colors.accent,
    },
    benefitText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 20,
      color: Colors.textSecondary,
      fontWeight: '600',
    },
    button: {
      backgroundColor: Colors.accent,
      borderRadius: 18,
      paddingVertical: 15,
      paddingHorizontal: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    buttonPressed: sharedPressedScale,
    buttonText: {
      color: Colors.white,
      fontSize: 15,
      fontWeight: '900',
    },
    brandPill: {
      ...sharedBrandPillBase,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      marginBottom: 12,
    },
    brandDot: {
      ...sharedBrandDotBase,
      backgroundColor: Colors.logoGreenLight,
    },
    brandPillText: {
      ...sharedBrandPillTextBase,
      color: Colors.white,
      textTransform: 'uppercase',
    },
    heroHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    heroSubtitle: {
      marginTop: 10,
      maxWidth: 290,
      color: 'rgba(255,255,255,0.72)',
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '600',
    },
  }),
);

export const createHomeDashboardStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    errorBanner: {
      margin: 16,
      padding: 16,
      backgroundColor: '#FEF2F2',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#FECACA',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    errorText: {
      color: '#DC2626',
      fontSize: 14,
      fontFamily: 'Inter_400Regular',
      flex: 1,
      lineHeight: 20,
    },
    // content: {
      // paddingBottom: 32,
    // },
    hero: {
      minHeight: 260,
      borderRadius: 30,
      overflow: 'hidden',
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 26,
      backgroundColor: Colors.accentDark,
    },
    heroOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 34, 24, 0.56)',
    },
    heroGlow: {
      position: 'absolute',
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: 'rgba(79, 196, 122, 0.20)',
      top: -60,
      right: -50,
    },
    heroHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    
    brandPill: {
      ...sharedBrandPillBase,
      borderColor: 'rgba(255, 255, 255, 0.14)',
      backgroundColor: 'rgba(0, 23, 28, 0.63)',
    },
    helpPillText: {
      color: Colors.white,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '900',
    },
    heroBody: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 16,
    },
    heroCopy: {
      flex: 1,
    },
    kicker: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 10,
    },
    heroTitle: {
      color: Colors.textOnDark,
      fontSize: 32,
      lineHeight: 38,
      fontWeight: '900',
      letterSpacing: -0.9,
    },
    heroSubtitle: {
      marginTop: 12,
      color: 'rgba(255,255,255,0.82)',
      fontSize: 14,
      lineHeight: 21,
      maxWidth: 330,
    },
    // avatarImage: {
    //   ...sharedAvatarImageFill,
    // },
    quickActionsRow: {
      marginHorizontal: 18,
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      marginVertical: 8,
    },
    quickAction: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 6,
    },
    quickActionIconBox: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: Colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    quickActionLabel: {
      color: Colors.textSecondary,
      fontSize: 11,
      fontWeight: '600',
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    section: {
      marginHorizontal: 18,
      marginTop: 15,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 23,
      fontWeight: '600',
      letterSpacing: -0.7,
    },
    sectionSubtitle: {
      color: Colors.textMuted,
      fontSize: 13,
      marginTop: 4,
      fontWeight: '600',
    },
    linkButton: {
      paddingVertical: 6,
    },
    linkText: {
      color: Colors.accent,
      fontSize: 13,
      fontWeight: '800',
    },
   
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    locationText: {
      flex: 1,
      color: Colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
   
    reservePill: {
      backgroundColor: Colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
    },
    reservePillText: {
      color: Colors.textOnDark,
      fontSize: 12,
      fontWeight: '900',
    },
    locationChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: Colors.surface,
      borderRadius: 500,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: Colors.border,
      marginEnd: 12,
      marginBottom: 15,
    },
    dateText: {
      marginTop: 8,
      fontSize: 13,
      backgroundColor: Colors.surfaceMuted,
      color: '#666',
      padding: 10
    },
    locationInitialsText: {
      color: Colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
    },
    locationChipText: {
      color: Colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
      maxWidth: 140,
    },
    pressed: sharedPressedScale,

    // loginPillText: sharedLoginPillText,
    // loginPill: {
    //   ...sharedLoginPillBase,
    //   backgroundColor: Colors.primary,
    //   borderColor: 'rgba(255,255,255,0.35)',
    // },
    // headerActionPressed: sharedHeaderActionPressed,
    // avatar: {
    //   ...sharedSmallAvatarBase,
    //   backgroundColor: Colors.primaryLight,
    //   borderColor: 'rgba(255,255,255,0.24)',
    // },
  }),
);

export const createPropertiesScreenStyles = (Colors: AppColors) =>
  StyleSheet.create({
    // Root
    root: {
      flex: 1,
      backgroundColor: Colors.background,
    },
 
    // ── Fixed Header ────────────────────────────────────────────────────────
    header: {
      backgroundColor: Colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: Colors.border,
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: Colors.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 12,
    },

    // Filter chips
    filters: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 10,
    },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: Colors.border,
      backgroundColor: Colors.background,
    },
    chipActive: {
      backgroundColor: Colors.accent,
      borderColor: Colors.accent,
    },
    chipText: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.textSecondary,
    },
    chipTextActive: {
      color: '#fff',
    },

    // ── List ────────────────────────────────────────────────────────────────
    list: {
      paddingBottom: 24,
    },
 
    // Sub-header row (count + sort)
    subHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 8,
    },
    resultCount: {
      fontSize: 13,
      color: Colors.textMuted,
      fontWeight: '500',
    },
    sortBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    sortText: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.accent,
    },
 
    // Error banner
    errorBanner: {
      marginHorizontal: 16,
      marginBottom: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: '#FEF2F2',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#FECACA',
    },
    errorText: {
      fontSize: 13,
      color: '#DC2626',
    },

    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
 
    // Empty state
    empty: {
      alignItems: 'center',
      paddingTop: 64,
      paddingHorizontal: 32,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: Colors.textPrimary,
      marginTop: 12,
      marginBottom: 4,
    },
    emptyText: {
      fontSize: 14,
      lineHeight: 20,
      color: Colors.textMuted,
      textAlign: 'center',
    },
  });

export const createInvestorDashboardStyles = createThemedStyles((Colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scroll: { flex: 1, backgroundColor: Colors.background },
    scrollContent: { paddingBottom: 98 },
    heroShell: {
      marginHorizontal: 18,
      backgroundColor: Colors.primary,
      borderRadius: 30,
      overflow: 'hidden',
      paddingHorizontal: 22,
      paddingTop: 22,
      paddingBottom: 24,
    },
    heroDecorCircleOne: {
      ...sharedHeroDecorCircleOne,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    heroDecorCircleTwo: {
      ...sharedHeroDecorCircleTwo,
      borderColor: 'rgba(255,255,255,0.12)',
      bottom: -92,
    },
    heroHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    // heroKicker: {
    //   fontSize: 13,
    //   fontWeight: '800',
    //   color: 'rgba(255,255,255,0.76)',
    //   textTransform: 'uppercase',
    //   letterSpacing: 0.8,
    //   marginBottom: 8,
    // },
    heroTitle: {
      color: Colors.white,
      fontSize: 32,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    heroIconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: Colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    heroCard: {
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderRadius: 24,
      padding: 22,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
    },
    heroLeft: { flex: 1 },
    heroLabel: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    heroValue: {
      color: Colors.white,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 10,
    },
    heroBadge: {
      backgroundColor: Colors.accent,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      alignSelf: 'flex-start',
    },
    heroBadgeText: {
      color: Colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    heroRight: { marginLeft: 16 },
    miniCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      borderWidth: 2,
      borderColor: Colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.primaryLight,
    },
    miniCircleVal: {
      color: Colors.white,
      fontSize: 22,
      fontWeight: '800',
    },
    miniCircleLabel: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: 10,
      fontWeight: '600',
      marginTop: -2,
    },
    statsRow: {
      paddingHorizontal: 18,
      gap: 12,
      paddingTop: 18,
      paddingBottom: 4,
      marginBottom: 6,
    },
    statCard: {
      backgroundColor: Colors.surface,
      borderRadius: 20,
      padding: 16,
      width: 130,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    statLabel: {
      fontSize: 11,
      color: Colors.textMuted,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    statValue: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 8,
    },
    statBadge: {
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
      alignSelf: 'flex-start',
    },
    statBadgePos: { backgroundColor: Colors.tag },
    statBadgeNeg: { backgroundColor: '#FEF2F2' },
    statChange: { fontSize: 11, fontWeight: '700' },
    statChangePos: { color: Colors.tagText },
    statChangeNeg: { color: Colors.error },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 18,
      marginTop: 24,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: Colors.textPrimary,
      letterSpacing: -0.4,
    },
    sectionAction: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.accent,
    },
    qaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      gap: 12,
    },
    qaItem: { flex: 1, alignItems: 'center' },
    qaIconBox: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: Colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    qaLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: Colors.textSecondary,
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    propCard: {
      marginHorizontal: 18,
      marginBottom: 12,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      overflow: 'hidden',
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.05,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 3 },
      elevation: 3,
    },
    propStrip: {
      width: 4,
      backgroundColor: Colors.accent,
    },
    propContent: {
      flex: 1,
      padding: 16,
    },
    propTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    propName: {
      fontSize: 17,
      fontWeight: '900',
      color: Colors.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 6,
    },
    propLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    propLocation: {
      flex: 1,
      fontSize: 12,
      color: Colors.textMuted,
      fontWeight: '600',
    },
    statusBadge: {
      borderRadius: 8,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    saleStatus: { backgroundColor: Colors.tag },
    leaseStatus: { backgroundColor: '#FEF9EC' },
    statusText: { fontSize: 11, fontWeight: '700' },
    saleStatusText: { color: Colors.tagText },
    leaseStatusText: { color: '#92400E' },
    propDivider: {
      height: 1,
      backgroundColor: Colors.border,
      marginVertical: 12,
      opacity: 0.5,
    },
    propMetrics: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    propMetric: { flex: 1, alignItems: 'center' },
    metricLabel: {
      fontSize: 10,
      color: Colors.textMuted,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 3,
    },
    metricValue: {
      fontSize: 13,
      fontWeight: '800',
      color: Colors.textPrimary,
      letterSpacing: -0.2,
    },
    metricSep: {
      width: 1,
      height: 28,
      backgroundColor: Colors.border,
      opacity: 0.5,
    },
    propFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    typeBadge: {
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    typeBadgeText: { fontSize: 11, fontWeight: '700' },
    acquiredText: {
      fontSize: 11,
      color: Colors.textMuted,
      fontWeight: '500',
    },
    txCard: {
      marginHorizontal: 18,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: Colors.border,
      shadowColor: Colors.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    txRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      gap: 12,
    },
    txIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    txIconPos: { backgroundColor: Colors.tag },
    txIconNeg: { backgroundColor: '#FEF2F2' },
    txLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.textPrimary,
      marginBottom: 2,
    },
    txDate: { fontSize: 11, color: Colors.textMuted, fontWeight: '500' },
    txAmount: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
    txPos: { color: Colors.accent },
    txNeg: { color: Colors.error },
    txDivider: {
      height: 1,
      backgroundColor: Colors.border,
      opacity: 0.4,
    },
  }),
);
