import { AppColors } from '@/constants/colors';
import { StyleSheet } from 'react-native';

import { createThemedStyles } from './foundations';

export const createPropertyDetailStyles = createThemedStyles((Colors: AppColors) => ({
  modalStyles: StyleSheet.create({
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
    },
    closeText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
    counter: { color: '#FFF', fontSize: 14, fontWeight: '600' },
    dotsRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 16,
      gap: 6,
    },
    dot: { width: 8, height: 8, borderRadius: 4 },
    dotActive: { backgroundColor: '#FFF' },
    dotInactive: { backgroundColor: 'rgba(255,255,255,0.35)' },
    thumbnails: {
      paddingHorizontal: 16,
      paddingTop: 16,
      gap: 8,
    },
    thumb: {
      width: 64,
      height: 64,
      borderRadius: 8,
      opacity: 0.5,
    },
    thumbActive: {
      opacity: 1,
      borderWidth: 2,
      borderColor: '#FFF',
    },
  }),
  styles: StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.background },
    notFound: {
      textAlign: 'center',
      marginTop: 80,
      fontSize: 16,
      color: Colors.textMuted,
    },
    imageWrap: { position: 'relative' },
    image: { width: '100%', height: 280, backgroundColor: Colors.border },
    backBtn: {
      position: 'absolute',
      top: 16,
      left: 16,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.92)',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    badge: {
      position: 'absolute',
      top: 16,
      right: 16,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
    },
    rentBadge: { backgroundColor: Colors.rentBadge },
    saleBadge: { backgroundColor: Colors.saleBadge },
    badgeText: { fontSize: 12, fontWeight: '700' },
    rentBadgeText: { color: Colors.rentBadgeText },
    saleBadgeText: { color: Colors.saleBadgeText },
    content: { padding: 20, paddingBottom: 100 },
    price: {
      fontSize: 26,
      fontWeight: '800',
      color: Colors.accent,
      marginBottom: 6,
    },
    title: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors.textPrimary,
      marginBottom: 6,
      lineHeight: 26,
    },
    address: {
      fontSize: 14,
      color: Colors.textSecondary,
      marginBottom: 20,
    },
    specsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
    specCard: {
      flex: 1,
      backgroundColor: Colors.surface,
      borderRadius: 12,
      padding: 14,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
    },
    specIcon: { fontSize: 22, marginBottom: 6 },
    specLabel: {
      fontSize: 12,
      color: Colors.textSecondary,
      fontWeight: '600',
      textAlign: 'center',
    },
    tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
    tag: {
      backgroundColor: Colors.tag,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    tagText: { fontSize: 12, color: Colors.tagText, fontWeight: '600' },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: Colors.textPrimary,
      marginBottom: 10,
    },
    description: {
      fontSize: 14,
      color: Colors.textSecondary,
      lineHeight: 22,
      marginBottom: 24,
    },
    agentCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    agentAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: Colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    agentAvatarText: { color: '#FFF', fontWeight: '700', fontSize: 16 },
    agentInfo: { flex: 1 },
    agentName: {
      fontSize: 15,
      fontWeight: '700',
      color: Colors.textPrimary,
      marginBottom: 2,
    },
    agentPhone: { fontSize: 13, color: Colors.textSecondary },
    callBtn: {
      backgroundColor: Colors.tag,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    callBtnText: { fontSize: 13, color: Colors.tagText, fontWeight: '700' },
    cta: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      padding: 16,
      paddingBottom: 28,
      backgroundColor: Colors.background,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
    },
    inquireBtn: {
      backgroundColor: Colors.accent,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
    },
    inquireBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
    viewImagesBtn: {
      position: 'absolute',
      bottom: 12,
      right: 12,
      backgroundColor: 'rgba(0,0,0,0.6)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    viewImagesBtnText: { color: '#FFF', fontSize: 13, fontWeight: '700' },
  }),
}));
