import { AppColors, Colors } from '@/constants/colors';
import { Dimensions, StyleSheet } from 'react-native';

import { createThemedStyles } from './foundations';

export const createPropertyDetailStyles = createThemedStyles((Colors: AppColors) => ({
  modalStyles: StyleSheet.create({
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
    },
    closeText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
    counter: { color: '#FFF', fontSize: 14, fontWeight: '600' },
    dotsRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 16,
      gap: 6,
    },
    dot: { width: 8, height: 8, borderRadius: 4 },
    dotActive: { backgroundColor: '#FFF' },
    dotInactive: { backgroundColor: 'rgba(255,255,255,0.35)' },
    thumbnails: {
      paddingHorizontal: 16,
      paddingTop: 16,
      gap: 8,
    },
    thumb: {
      width: 64,
      height: 64,
      borderRadius: 8,
      opacity: 0.5,
    },
    thumbActive: {
      opacity: 1,
      borderWidth: 2,
      borderColor: '#FFF',
    },
  }),
  styles: StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.background },
    notFound: {
      textAlign: 'center',
      marginTop: 80,
      fontSize: 16,
      color: Colors.textMuted,
    },
    imageWrap: { position: 'relative' },
    image: { width: '100%', height: 280, backgroundColor: Colors.border },
    backBtn: {
      position: 'absolute',
      top: 16,
      left: 16,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.92)',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    badge: {
      position: 'absolute',
      top: 16,
      right: 16,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
    },
    rentBadge: { backgroundColor: Colors.rentBadge },
    saleBadge: { backgroundColor: Colors.saleBadge },
    badgeText: { fontSize: 12, fontWeight: '700' },
    rentBadgeText: { color: Colors.rentBadgeText },
    saleBadgeText: { color: Colors.saleBadgeText },
    content: { padding: 20, paddingBottom: 100 },
    price: {
      fontSize: 26,
      fontWeight: '800',
      color: Colors.accent,
      marginBottom: 6,
    },
    title: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors.textPrimary,
      marginBottom: 6,
      lineHeight: 26,
    },
    address: {
      fontSize: 14,
      color: Colors.textSecondary,
      marginBottom: 20,
    },
    specsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
    specCard: {
      flex: 1,
      backgroundColor: Colors.surface,
      borderRadius: 12,
      padding: 14,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
    },
    specIcon: { fontSize: 22, marginBottom: 6 },
    specLabel: {
      fontSize: 12,
      color: Colors.textSecondary,
      fontWeight: '600',
      textAlign: 'center',
    },
    tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
    tag: {
      backgroundColor: Colors.tag,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    tagText: { fontSize: 12, color: Colors.tagText, fontWeight: '600' },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: Colors.textPrimary,
      marginBottom: 10,
    },
    description: {
      fontSize: 14,
      color: Colors.textSecondary,
      lineHeight: 22,
      marginBottom: 24,
    },
    agentCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    agentAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: Colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    agentAvatarText: { color: '#FFF', fontWeight: '700', fontSize: 16 },
    agentInfo: { flex: 1 },
    agentName: {
      fontSize: 15,
      fontWeight: '700',
      color: Colors.textPrimary,
      marginBottom: 2,
    },
    agentPhone: { fontSize: 13, color: Colors.textSecondary },
    callBtn: {
      backgroundColor: Colors.tag,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    callBtnText: { fontSize: 13, color: Colors.tagText, fontWeight: '700' },
    cta: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      padding: 16,
      paddingBottom: 28,
      backgroundColor: Colors.background,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
    },
    inquireBtn: {
      backgroundColor: Colors.accent,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
    },
    inquireBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
    viewImagesBtn: {
      position: 'absolute',
      bottom: 12,
      right: 12,
      backgroundColor: 'rgba(0,0,0,0.6)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    viewImagesBtnText: { color: '#FFF', fontSize: 13, fontWeight: '700' },
  }),
}));

export const PROPERTY_SCREEN_WIDTH = Dimensions.get('window').width;
export const PAGE_PADDING = 15;
export const CAROUSEL_HEIGHT = 300;

export const propertyDetailsStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  topBar: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: PAGE_PADDING,
    backgroundColor: Colors.background,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  pressed: {
    opacity: 0.78,
  },
  backButtonGhost: {
    width: 42,
    height: 42,
  },
  topTitleBlock: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  topTitle: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  topSubtitle: {
    marginTop: 3,
    maxWidth: '100%',
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  carouselSection: {
    paddingTop: 4,
    paddingBottom: 14,
  },
  carouselCard: {
    width: PROPERTY_SCREEN_WIDTH,
    height: CAROUSEL_HEIGHT,
    paddingHorizontal: PAGE_PADDING,
  },
  carouselImage: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    backgroundColor: Colors.border,
  },
  carouselMeta: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  imageCountPill: {
    position: 'absolute',
    left: PAGE_PADDING,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Colors.primary,
  },
  imageCountText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: '900',
  },
  dots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D9D9D9',
  },
  activeDot: {
    width: 22,
    backgroundColor: Colors.tagText,
  },
  summaryCard: {
    marginHorizontal: PAGE_PADDING,
    padding: 16,
    borderRadius: 22,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  summaryTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  summaryCopy: {
    flex: 1,
    minWidth: 0,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  categoryBadge: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Colors.tag,
  },
  categoryText: {
    color: Colors.tagText,
    fontSize: 11,
    fontWeight: '900',
  },
  statusBadge: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Colors.primary,
  },
  statusText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: '900',
  },
  priceLabel: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 3,
  },
  price: {
    color: Colors.accent,
    fontSize: 27,
    fontWeight: '900',
  },
  title: {
    marginTop: 7,
    color: Colors.textPrimary,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
  },
  sidePanel: {
    width: 86,
    minHeight: 106,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 18,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sideValue: {
    marginTop: 8,
    color: Colors.textPrimary,
    fontSize: 17,
    fontWeight: '900',
  },
  sideLabel: {
    marginTop: 2,
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  locationRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  locationIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.tag,
  },
  location: {
    flex: 1,
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: PAGE_PADDING,
    marginTop: 14,
  },
  statItem: {
    flex: 1,
    minHeight: 98,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 18,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  statIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.tag,
    marginBottom: 7,
  },
  statValue: {
    maxWidth: '100%',
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  statLabel: {
    marginTop: 4,
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  section: {
    marginHorizontal: PAGE_PADDING,
    marginTop: 18,
  },
  sectionTitle: {
    marginBottom: 12,
    color: Colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  paymentCard: {
    overflow: 'hidden',
    borderRadius: 22,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  monthlyBlock: {
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    backgroundColor: Colors.primary,
  },
  monthlyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  monthlyCopy: {
    flex: 1,
    minWidth: 0,
  },
  monthlyLabel: {
    color: 'rgba(255, 255, 255, 0.72)',
    fontSize: 12,
    fontWeight: '800',
  },
  monthlyValue: {
    marginTop: 5,
    color: Colors.white,
    fontSize: 23,
    fontWeight: '900',
  },
  breakdownList: {
    paddingHorizontal: 16,
  },
  breakdownRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  lastRow: {
    borderBottomWidth: 0,
  },
  breakdownLabel: {
    flex: 1,
    color: Colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  breakdownValue: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  amenitiesCard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 14,
    borderRadius: 22,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  amenityChip: {
    minHeight: 42,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: Colors.tag,
    borderWidth: 1,
    borderColor: 'rgba(0, 140, 79, 0.16)',
  },
  amenityIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.accent,
  },
  amenityText: {
    flexShrink: 1,
    color: Colors.tagText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  description: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 23,
    fontWeight: '600',
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: Colors.background,
  },
  stateTitle: {
    marginTop: 12,
    color: Colors.textPrimary,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  stateText: {
    marginTop: 8,
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
    textAlign: 'center',
  },
  actionBar: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: PAGE_PADDING,
    paddingTop: 12,
    paddingBottom: 50,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  secondaryAction: {
    flex: 1,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.accent,
    backgroundColor: Colors.surface,
  },
  activeInquiryAction: {
    backgroundColor: Colors.tag,
  },
  primaryAction: {
    flex: 1.1,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    backgroundColor: Colors.accent,
  },
  secondaryActionText: {
    color: Colors.accent,
    fontSize: 14,
    fontWeight: '900',
  },
  primaryActionText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '900',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
  },
  inquirySheet: {
    maxHeight: '88%',
    paddingTop: 10,
    paddingHorizontal: PAGE_PADDING,
    paddingBottom: 30,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: Colors.surface,
  },
  scheduleSheet: {
    maxHeight: '90%',
    paddingTop: 10,
    paddingHorizontal: PAGE_PADDING,
    paddingBottom: 30,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: Colors.surface,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: Colors.border,
    marginBottom: 16,
  },
  inquiryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  inquiryIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.tag,
  },
  scheduleIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.tag,
  },
  inquiryHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  inquiryTitle: {
    color: Colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  inquirySubtitle: {
    marginTop: 3,
    color: Colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
  },
  inquiryForm: {
    gap: 12,
    paddingBottom: 8,
  },
  scheduleForm: {
    gap: 14,
    paddingBottom: 8,
  },
  visitHero: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    padding: 14,
    borderRadius: 18,
    backgroundColor: Colors.primary,
  },
  visitHeroIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  visitHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  visitHeroLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontWeight: '800',
  },
  visitHeroText: {
    marginTop: 4,
    color: Colors.white,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
  },
  scheduleGroup: {
    gap: 9,
  },
  scheduleGroupLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '900',
  },
  schedulePickerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  schedulePickerField: {
    flex: 1,
    gap: 7,
  },
  schedulePickerInput: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.background,
  },
  schedulePickerInputText: {
    flex: 1,
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  schedulePickerPlaceholder: {
    color: Colors.textMuted,
  },
  schedulePickerModalRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  schedulePickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  schedulePickerCard: {
    width: '100%',
    maxWidth: 360,
    padding: 22,
    borderRadius: 24,
    backgroundColor: Colors.surface,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 8,
  },
  schedulePickerTitle: {
    color: Colors.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 18,
  },
  schedulePickerColumns: {
    minHeight: 178,
    flexDirection: 'row',
    gap: 10,
  },
  schedulePickerColumnFrame: {
    flex: 1,
    height: 178,
    overflow: 'hidden',
    borderRadius: 14,
    backgroundColor: Colors.background,
  },
  schedulePickerSelectionFrame: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 68,
    height: 42,
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: Colors.accent,
    backgroundColor: 'rgba(0, 140, 79, 0.07)',
  },
  schedulePickerColumn: {
    flex: 1,
    maxHeight: 178,
  },
  schedulePickerColumnContent: {
    paddingVertical: 68,
  },
  schedulePickerOption: {
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  schedulePickerOptionText: {
    color: Colors.textMuted,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  schedulePickerOptionTextSelected: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  schedulePickerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 18,
    marginTop: 18,
  },
  schedulePickerAction: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  schedulePickerCancelText: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
  },
  schedulePickerConfirmText: {
    color: Colors.accent,
    fontSize: 14,
    fontWeight: '900',
  },
  scheduleDivider: {
    height: 1,
    backgroundColor: Colors.border,
  },
  inputGroup: {
    gap: 7,
  },
  inputLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '900',
  },
  input: {
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.background,
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  messageInput: {
    minHeight: 108,
    textAlignVertical: 'top',
  },
  visitNotesInput: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  inquiryActions: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 14,
  },
  cancelInquiryButton: {
    flex: 1,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  submitInquiryButton: {
    flex: 1.35,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: Colors.accent,
  },
  submitInquiryButtonDisabled: {
    backgroundColor: Colors.border,
  },
  disabledButton: {
    opacity: 0.72,
  },
  cancelInquiryText: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontWeight: '900',
  },
  submitInquiryText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '900',
  },
  submitInquiryTextDisabled: {
    color: Colors.textMuted,
  },
});
